language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - ~/.npm
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local_dir: public
  target_branch: master
  keep-history: true
  on:
    branch: lumen

before_script:
  - 'npm i -g gatsby-cli'
  - 'yarn'

script:
  - gatsby build
