language: node_js
node_js:
  - "lts"
cache: yarn

install: yarn

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   local_dir: public
#   keep-history: true
#   on:
#     branch: master


script:
  - "gatsby build"
